
#server.port: 9100
server.servlet.context-path: /api


BASE_LOCATION: /Users/teresa/Program/Code/zyxt/java_book
#DB_NAME: java_book

springfox:
  documentation:
    swagger-ui:
      # 生产环境需要关闭
      enabled: true



File:
#  uploadPath: ${BASE_LOCATION}\server\upload
  uploadPath: ${BASE_LOCATION}/server/upload
#  /Users/teresa/Program/Code/zyxt/java_book/server/upload
#
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/java_book?useSSL=false&serverTimezone=UTC
#    username: root
#    password: 12345678
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      initial-size: 5
#      min-idle: 5
#      max-active: 20
#      max-wait: 60000
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 1 FROM DUAL
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 20
#      filters: stat,wall,log4j

server:
  port: 9100
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

spring:
  datasource:
    url : jdbc:mysql://123.60.10.11:3306/java_book2
    username : root
    password : Zhlyc123.
    driverClassName : com.mysql.cj.jdbc.Driver
